name = "StatProfilerHTML"
uuid = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"
author = ["Timo Kluck <tkluck@infty.nl>"]
version = "0.5.0"

[compat]
julia = "1.0"

[deps]
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
